In [1]:
import pandas as pd

In [7]:
rating = pd.read_csv('/workspaces/Data-Science/dados/ratings.csv')

In [8]:
rating

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [9]:
rating.shape

(100836, 4)

alterar nome das colunas

In [11]:
rating.columns   = ["id_user", "filme_id", "nota", "momento"]
rating.head()

   id_user  filme_id  nota    momento
0        1         1   4.0  964982703
1        1         3   4.0  964981247
2        1         6   4.0  964982224
3        1        47   5.0  964983815
4        1        50   5.0  964982931

In [14]:
rating["nota"].unique()

array([4. , 5. , 3. , 2. , 1. , 4.5, 3.5, 2.5, 0.5, 1.5])

In [15]:
rating["nota"].value_counts()

nota
4.0    26818
3.0    20047
5.0    13211
3.5    13136
4.5     8551
2.0     7551
2.5     5550
1.0     2811
1.5     1791
0.5     1370
Name: count, dtype: int64

In [16]:
rating["nota"].mean()

np.float64(3.501556983616962)